spring.application.name=order-service

order.message=thisisorder
server.port=8081

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

# Custom properties
order.discount.rate=10
order.tax.rate=18

# RabbitMQ (if using)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
